<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Wine</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: left;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
            <h1>Id: <?= htmlspecialchars($id); ?></h1>
            <h2>Name: <?= htmlspecialchars($name); ?></h2>
            <h2>Year: <?= htmlspecialchars($year); ?></h2>
            <h2>grapes: <?= htmlspecialchars($grapes); ?>    </h2>
            <h2>country: <?= htmlspecialchars($country); ?>    </h2>
            <h2>region: <?= htmlspecialchars($region); ?>    </h2>
            <h2>description: <?= htmlspecialchars($description); ?>    </h2>
            <h2>picture: <?= htmlspecialchars($picture); ?>    </h2>
    </body>
</html>

